DROP TABLE IF EXISTS task_chunks;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS agents;
DROP TABLE IF EXISTS planets;
DROP TABLE IF EXISTS galaxies;
DROP TABLE IF EXISTS users;
