// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	auth "github.com/stellaris/stellaris/server/internal/handler/auth"
	galaxy "github.com/stellaris/stellaris/server/internal/handler/galaxy"
	planet "github.com/stellaris/stellaris/server/internal/handler/planet"
	session "github.com/stellaris/stellaris/server/internal/handler/session"
	wsHandler "github.com/stellaris/stellaris/server/internal/handler/ws"
	"github.com/stellaris/stellaris/server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/galaxy/create",
				Handler: galaxy.CreateGalaxyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/galaxy/:gid/agents",
				Handler: galaxy.GalaxyAgentsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.UserJwt.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/planet/join",
				Handler: planet.PlanetJoinHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/planet/heartbeat",
				Handler: planet.PlanetHeartbeatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/planet/agent/register",
				Handler: planet.AgentRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/planet/agent/unregister",
				Handler: planet.AgentUnregisterHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.PlanetJwt.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/session/:session_uuid/history",
				Handler: session.SessionHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/session/:session_uuid/message",
				Handler: session.SessionMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/session/create",
				Handler: session.SessionCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/session/:session_uuid/ws-ticket",
				Handler: session.SessionWSTicketHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.UserJwt.AccessSecret),
	)

	// WebSocket 路由：handler 自己验证 token，不走 go-zero JWT 中间件。
	server.AddRoutes([]rest.Route{
		{
			Method:  http.MethodGet,
			Path:    "/ws/session/:session_uuid",
			Handler: wsHandler.SessionWSHandler(serverCtx),
		},
	})
}
