// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AgentInfo struct {
	AgentUUID        string                 `json:"agent_uuid"`
	Type             string                 `json:"type"`
	Name             string                 `json:"name"`
	Models           []string               `json:"models"`
	CapabilitiesJSON map[string]interface{} `json:"capabilities"`
	Status           string                 `json:"status"`
}

type GalaxyCreateReq struct {
	Name string `json:"name"`
}

type GalaxyCreateResp struct {
	GID       string `json:"gid"`
	NodeToken string `json:"node_token"`
}

type HeartbeatReq struct {
	Agents []AgentInfo `json:"agents"`
	CPU    float64     `json:"cpu"`
	Mem    float64     `json:"mem"`
}

type HeartbeatResp struct {
	OK bool `json:"ok"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type PlanetJoinReq struct {
	GID       string `json:"gid"`
	NodeToken string `json:"node_token"`
	Hostname  string `json:"hostname"`
	IP        string `json:"ip"`
	OS        string `json:"os"`
}

type PlanetJoinResp struct {
	PlanetUUID string `json:"planet_uuid"`
	PlanetJwt  string `json:"planet_jwt"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Token string `json:"token"`
}

type SessionCreateReq struct {
	GID        string   `json:"gid"`
	Mode       string   `json:"mode"`
	AgentUUIDs []string `json:"agent_uuids"`
	DSL        string   `json:"dsl,omitempty"`
}

type SessionCreateResp struct {
	SessionUUID string `json:"session_uuid"`
}

type SessionHistoryReq struct {
	SessionUUID string `path:"session_uuid"`
}

type SessionHistoryResp struct {
	Tasks []TaskOutput `json:"tasks"`
}

type SessionMessageReq struct {
	SessionUUID string `path:"session_uuid"`
	Content     string `json:"content"`
}

type SessionMessageResp struct {
	MessageID int64    `json:"message_id"`
	TaskUUIDs []string `json:"task_uuids"`
}

type TaskChunk struct {
	Seq   int    `json:"seq"`
	Type  string `json:"type"`
	Chunk string `json:"chunk"`
	TS    int64  `json:"ts"`
}

type TaskOutput struct {
	TaskUUID       string      `json:"task_uuid"`
	Status         string      `json:"status"`
	AgentUUID      string      `json:"agent_uuid"`
	Chunks         []TaskChunk `json:"chunks"`
	ParentTaskUUID string      `json:"parent_task_uuid,omitempty"`
	NodeID         string      `json:"node_id,omitempty"`
}

type WSTicketReq struct {
	SessionUUID string `path:"session_uuid"`
}

type WSTicketResp struct {
	Ticket string `json:"ticket"`
}
